//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Scripts/Controls/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Menu"",
            ""id"": ""0f506879-3d77-40dc-9568-03dfdcd4005d"",
            ""actions"": [
                {
                    ""name"": ""showHide"",
                    ""type"": ""Button"",
                    ""id"": ""cc669642-a864-4328-a322-846d329b3db2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dadd05e7-720d-43ee-9a58-4a0e18a5484e"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""showHide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e49c5d3-e371-4522-9581-b6cc640109b1"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""showHide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""World"",
            ""id"": ""bcc6c8d3-48b5-4080-80b5-7ffc101a980e"",
            ""actions"": [
                {
                    ""name"": ""move"",
                    ""type"": ""Value"",
                    ""id"": ""109615f3-2f96-426d-9691-b342e726481e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""sprint"",
                    ""type"": ""Button"",
                    ""id"": ""8b20e364-e444-44db-8e8a-adc250195725"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""cameraTurn"",
                    ""type"": ""Value"",
                    ""id"": ""a8b8d67b-c1ee-4332-9545-c02dc5d86ebc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""interact"",
                    ""type"": ""Button"",
                    ""id"": ""b8893bc8-6c35-405b-9a97-8e0954199031"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""minimap"",
                    ""type"": ""Button"",
                    ""id"": ""2303d92d-950d-410d-a8d3-a5d4479bcbaf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""36cf71d7-04a9-4b47-85bc-f677226812b8"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""a32ac26e-6884-4b1f-99f1-bfa52b2827da"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""abb59b9e-530e-4f0a-8f9f-a1a11c4b1264"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""d555f72c-27cd-4e7b-a87a-143c35620406"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""f2c901a6-b232-4780-8f76-53154a4b3e41"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""25cb3b63-4267-4cca-b24d-11aea2f1ef08"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""961db870-bc2a-4bed-8428-06e01404a1f5"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""cameraTurn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4da7b94-10f2-4858-977c-c852921acdf2"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""cameraTurn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f7aed3a-5de2-4863-83b1-bb503e778b29"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c826d893-ea31-4808-ab20-9afff2cd195c"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4c93aae-8aaa-4845-b64d-82b3b2fb472f"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f354b499-7446-494e-8ea3-ad5085f06578"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c035f90-03e4-4e0e-abdb-ce7ddc79fd80"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""minimap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2533760e-9190-4313-bba8-567b88ffcab0"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""minimap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Combat"",
            ""id"": ""d09fb0c3-2de6-4b04-88fd-6809a69c43fa"",
            ""actions"": [
                {
                    ""name"": ""basic"",
                    ""type"": ""Button"",
                    ""id"": ""9710a28e-6286-421c-ae6e-1635fe978811"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""skill"",
                    ""type"": ""Button"",
                    ""id"": ""b8ad4090-0fee-4d19-a15a-1d56c858f44b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ult"",
                    ""type"": ""Button"",
                    ""id"": ""272221bf-2e6c-42d7-9b7b-aa0728532ee6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""use"",
                    ""type"": ""Button"",
                    ""id"": ""afa43ae5-3161-46d3-8223-d772ad42c210"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""moveSelLeft"",
                    ""type"": ""Button"",
                    ""id"": ""25e86188-0688-445c-b807-b282165b9242"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""moveSelRight"",
                    ""type"": ""Button"",
                    ""id"": ""13c014a4-4c65-47a9-ba13-8e5b7071e56f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4feb9f9a-290d-432d-9285-63967308fa41"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""basic"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1cd3d953-97a0-46d3-965e-164f8cbca12e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""basic"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46e2b208-e94a-4711-9562-916e79ab34ba"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""skill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""309dea7f-076b-4741-883c-52f9b8157181"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""skill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6213f98c-8012-4b80-9a7c-a9175e0218d2"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ult"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e8de435-23b0-4e6b-8072-da2c628c6cba"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ult"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""009caa54-f95d-4974-8d13-6bf87dfab08c"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""use"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""598368ce-d708-44dd-b061-9a53cecf4216"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""use"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aee7cd45-c800-4a62-ba7d-1be7d541bb2b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""use"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3bc2f9dc-7c75-4afa-b6d4-82f673ae9e6c"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveSelLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b50e9c42-bb0f-4b20-9b7e-8d1711e9a4b5"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveSelLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9aa60994-fc80-41b8-8e04-38842954631d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveSelLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23540e01-e393-4224-94c5-ece60028293d"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveSelLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""952c3201-f9ae-4234-a9dc-e3fc86b22bcd"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveSelRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0573c1fa-28eb-4459-987b-2210cd78de3a"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveSelRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6754d054-8f87-4e79-8cec-474293bd4a59"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveSelRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f7604ac-c5b2-4df4-85a3-a5ce6f9c4168"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveSelRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""InDev"",
            ""id"": ""46628c27-0fe6-4c97-bea3-4d2bb6685497"",
            ""actions"": [
                {
                    ""name"": ""cursorLockToggle"",
                    ""type"": ""Button"",
                    ""id"": ""22c46e02-ab0a-40b9-9bf9-8e5cb23ca9b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""edfb5c77-bc10-461b-8f52-18c4b8b0e95b"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""cursorLockToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Menu
        m_Menu = asset.FindActionMap("Menu", throwIfNotFound: true);
        m_Menu_showHide = m_Menu.FindAction("showHide", throwIfNotFound: true);
        // World
        m_World = asset.FindActionMap("World", throwIfNotFound: true);
        m_World_move = m_World.FindAction("move", throwIfNotFound: true);
        m_World_sprint = m_World.FindAction("sprint", throwIfNotFound: true);
        m_World_cameraTurn = m_World.FindAction("cameraTurn", throwIfNotFound: true);
        m_World_interact = m_World.FindAction("interact", throwIfNotFound: true);
        m_World_minimap = m_World.FindAction("minimap", throwIfNotFound: true);
        // Combat
        m_Combat = asset.FindActionMap("Combat", throwIfNotFound: true);
        m_Combat_basic = m_Combat.FindAction("basic", throwIfNotFound: true);
        m_Combat_skill = m_Combat.FindAction("skill", throwIfNotFound: true);
        m_Combat_ult = m_Combat.FindAction("ult", throwIfNotFound: true);
        m_Combat_use = m_Combat.FindAction("use", throwIfNotFound: true);
        m_Combat_moveSelLeft = m_Combat.FindAction("moveSelLeft", throwIfNotFound: true);
        m_Combat_moveSelRight = m_Combat.FindAction("moveSelRight", throwIfNotFound: true);
        // InDev
        m_InDev = asset.FindActionMap("InDev", throwIfNotFound: true);
        m_InDev_cursorLockToggle = m_InDev.FindAction("cursorLockToggle", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Menu
    private readonly InputActionMap m_Menu;
    private List<IMenuActions> m_MenuActionsCallbackInterfaces = new List<IMenuActions>();
    private readonly InputAction m_Menu_showHide;
    public struct MenuActions
    {
        private @InputActions m_Wrapper;
        public MenuActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @showHide => m_Wrapper.m_Menu_showHide;
        public InputActionMap Get() { return m_Wrapper.m_Menu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuActions set) { return set.Get(); }
        public void AddCallbacks(IMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_MenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MenuActionsCallbackInterfaces.Add(instance);
            @showHide.started += instance.OnShowHide;
            @showHide.performed += instance.OnShowHide;
            @showHide.canceled += instance.OnShowHide;
        }

        private void UnregisterCallbacks(IMenuActions instance)
        {
            @showHide.started -= instance.OnShowHide;
            @showHide.performed -= instance.OnShowHide;
            @showHide.canceled -= instance.OnShowHide;
        }

        public void RemoveCallbacks(IMenuActions instance)
        {
            if (m_Wrapper.m_MenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_MenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MenuActions @Menu => new MenuActions(this);

    // World
    private readonly InputActionMap m_World;
    private List<IWorldActions> m_WorldActionsCallbackInterfaces = new List<IWorldActions>();
    private readonly InputAction m_World_move;
    private readonly InputAction m_World_sprint;
    private readonly InputAction m_World_cameraTurn;
    private readonly InputAction m_World_interact;
    private readonly InputAction m_World_minimap;
    public struct WorldActions
    {
        private @InputActions m_Wrapper;
        public WorldActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @move => m_Wrapper.m_World_move;
        public InputAction @sprint => m_Wrapper.m_World_sprint;
        public InputAction @cameraTurn => m_Wrapper.m_World_cameraTurn;
        public InputAction @interact => m_Wrapper.m_World_interact;
        public InputAction @minimap => m_Wrapper.m_World_minimap;
        public InputActionMap Get() { return m_Wrapper.m_World; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WorldActions set) { return set.Get(); }
        public void AddCallbacks(IWorldActions instance)
        {
            if (instance == null || m_Wrapper.m_WorldActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_WorldActionsCallbackInterfaces.Add(instance);
            @move.started += instance.OnMove;
            @move.performed += instance.OnMove;
            @move.canceled += instance.OnMove;
            @sprint.started += instance.OnSprint;
            @sprint.performed += instance.OnSprint;
            @sprint.canceled += instance.OnSprint;
            @cameraTurn.started += instance.OnCameraTurn;
            @cameraTurn.performed += instance.OnCameraTurn;
            @cameraTurn.canceled += instance.OnCameraTurn;
            @interact.started += instance.OnInteract;
            @interact.performed += instance.OnInteract;
            @interact.canceled += instance.OnInteract;
            @minimap.started += instance.OnMinimap;
            @minimap.performed += instance.OnMinimap;
            @minimap.canceled += instance.OnMinimap;
        }

        private void UnregisterCallbacks(IWorldActions instance)
        {
            @move.started -= instance.OnMove;
            @move.performed -= instance.OnMove;
            @move.canceled -= instance.OnMove;
            @sprint.started -= instance.OnSprint;
            @sprint.performed -= instance.OnSprint;
            @sprint.canceled -= instance.OnSprint;
            @cameraTurn.started -= instance.OnCameraTurn;
            @cameraTurn.performed -= instance.OnCameraTurn;
            @cameraTurn.canceled -= instance.OnCameraTurn;
            @interact.started -= instance.OnInteract;
            @interact.performed -= instance.OnInteract;
            @interact.canceled -= instance.OnInteract;
            @minimap.started -= instance.OnMinimap;
            @minimap.performed -= instance.OnMinimap;
            @minimap.canceled -= instance.OnMinimap;
        }

        public void RemoveCallbacks(IWorldActions instance)
        {
            if (m_Wrapper.m_WorldActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IWorldActions instance)
        {
            foreach (var item in m_Wrapper.m_WorldActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_WorldActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public WorldActions @World => new WorldActions(this);

    // Combat
    private readonly InputActionMap m_Combat;
    private List<ICombatActions> m_CombatActionsCallbackInterfaces = new List<ICombatActions>();
    private readonly InputAction m_Combat_basic;
    private readonly InputAction m_Combat_skill;
    private readonly InputAction m_Combat_ult;
    private readonly InputAction m_Combat_use;
    private readonly InputAction m_Combat_moveSelLeft;
    private readonly InputAction m_Combat_moveSelRight;
    public struct CombatActions
    {
        private @InputActions m_Wrapper;
        public CombatActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @basic => m_Wrapper.m_Combat_basic;
        public InputAction @skill => m_Wrapper.m_Combat_skill;
        public InputAction @ult => m_Wrapper.m_Combat_ult;
        public InputAction @use => m_Wrapper.m_Combat_use;
        public InputAction @moveSelLeft => m_Wrapper.m_Combat_moveSelLeft;
        public InputAction @moveSelRight => m_Wrapper.m_Combat_moveSelRight;
        public InputActionMap Get() { return m_Wrapper.m_Combat; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CombatActions set) { return set.Get(); }
        public void AddCallbacks(ICombatActions instance)
        {
            if (instance == null || m_Wrapper.m_CombatActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CombatActionsCallbackInterfaces.Add(instance);
            @basic.started += instance.OnBasic;
            @basic.performed += instance.OnBasic;
            @basic.canceled += instance.OnBasic;
            @skill.started += instance.OnSkill;
            @skill.performed += instance.OnSkill;
            @skill.canceled += instance.OnSkill;
            @ult.started += instance.OnUlt;
            @ult.performed += instance.OnUlt;
            @ult.canceled += instance.OnUlt;
            @use.started += instance.OnUse;
            @use.performed += instance.OnUse;
            @use.canceled += instance.OnUse;
            @moveSelLeft.started += instance.OnMoveSelLeft;
            @moveSelLeft.performed += instance.OnMoveSelLeft;
            @moveSelLeft.canceled += instance.OnMoveSelLeft;
            @moveSelRight.started += instance.OnMoveSelRight;
            @moveSelRight.performed += instance.OnMoveSelRight;
            @moveSelRight.canceled += instance.OnMoveSelRight;
        }

        private void UnregisterCallbacks(ICombatActions instance)
        {
            @basic.started -= instance.OnBasic;
            @basic.performed -= instance.OnBasic;
            @basic.canceled -= instance.OnBasic;
            @skill.started -= instance.OnSkill;
            @skill.performed -= instance.OnSkill;
            @skill.canceled -= instance.OnSkill;
            @ult.started -= instance.OnUlt;
            @ult.performed -= instance.OnUlt;
            @ult.canceled -= instance.OnUlt;
            @use.started -= instance.OnUse;
            @use.performed -= instance.OnUse;
            @use.canceled -= instance.OnUse;
            @moveSelLeft.started -= instance.OnMoveSelLeft;
            @moveSelLeft.performed -= instance.OnMoveSelLeft;
            @moveSelLeft.canceled -= instance.OnMoveSelLeft;
            @moveSelRight.started -= instance.OnMoveSelRight;
            @moveSelRight.performed -= instance.OnMoveSelRight;
            @moveSelRight.canceled -= instance.OnMoveSelRight;
        }

        public void RemoveCallbacks(ICombatActions instance)
        {
            if (m_Wrapper.m_CombatActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICombatActions instance)
        {
            foreach (var item in m_Wrapper.m_CombatActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CombatActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CombatActions @Combat => new CombatActions(this);

    // InDev
    private readonly InputActionMap m_InDev;
    private List<IInDevActions> m_InDevActionsCallbackInterfaces = new List<IInDevActions>();
    private readonly InputAction m_InDev_cursorLockToggle;
    public struct InDevActions
    {
        private @InputActions m_Wrapper;
        public InDevActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @cursorLockToggle => m_Wrapper.m_InDev_cursorLockToggle;
        public InputActionMap Get() { return m_Wrapper.m_InDev; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InDevActions set) { return set.Get(); }
        public void AddCallbacks(IInDevActions instance)
        {
            if (instance == null || m_Wrapper.m_InDevActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InDevActionsCallbackInterfaces.Add(instance);
            @cursorLockToggle.started += instance.OnCursorLockToggle;
            @cursorLockToggle.performed += instance.OnCursorLockToggle;
            @cursorLockToggle.canceled += instance.OnCursorLockToggle;
        }

        private void UnregisterCallbacks(IInDevActions instance)
        {
            @cursorLockToggle.started -= instance.OnCursorLockToggle;
            @cursorLockToggle.performed -= instance.OnCursorLockToggle;
            @cursorLockToggle.canceled -= instance.OnCursorLockToggle;
        }

        public void RemoveCallbacks(IInDevActions instance)
        {
            if (m_Wrapper.m_InDevActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInDevActions instance)
        {
            foreach (var item in m_Wrapper.m_InDevActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InDevActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InDevActions @InDev => new InDevActions(this);
    public interface IMenuActions
    {
        void OnShowHide(InputAction.CallbackContext context);
    }
    public interface IWorldActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnCameraTurn(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnMinimap(InputAction.CallbackContext context);
    }
    public interface ICombatActions
    {
        void OnBasic(InputAction.CallbackContext context);
        void OnSkill(InputAction.CallbackContext context);
        void OnUlt(InputAction.CallbackContext context);
        void OnUse(InputAction.CallbackContext context);
        void OnMoveSelLeft(InputAction.CallbackContext context);
        void OnMoveSelRight(InputAction.CallbackContext context);
    }
    public interface IInDevActions
    {
        void OnCursorLockToggle(InputAction.CallbackContext context);
    }
}
